[ConnectServerInfo]
;==================================================
; Connection Settings
;==================================================
ConnectServerPortTCP = 44405
ConnectServerPortUDP = 55557
MaxConnectionIdle = 60
MaxConnectionPerIP = 5
MaxPacketPerSecond = 10